apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: cli
  name: oc-deploy-with-tag-deployment
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    This task will tag a specific image with the environment name.
    This will deploy the image if there is a Deployment trigger listening for the environment tag.
    This version works with Kubernetes Deployments (not DeploymentConfigs).
  params:
    - name: PROJECT
      description: The project namespace.
      type: string
      default: 9b301c
    - name: IMAGE_NAME
      description: The name given to the built image.
      type: string
    - name: IMAGE_TAG
      description: The tag given to the built image.
      type: string
      default: latest
    - name: ENV
      description: The environment to deploy to.
      type: string
    - name: TIMEOUT
      description: The timeout before it will stop waiting for the pod to become available.
      type: string
      default: '600s'
    - name: OBJECT
      description: The kubernetes object that will be deployed [deployment|sts]
      type: string
      default: deployment

  steps:
    - name: deploy
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
      resources: {}
      script: |
        set -xe
        echo "Tagging image to trigger deployment to $(params.ENV)"
        oc tag $(params.IMAGE_NAME):$(params.IMAGE_TAG) $(params.IMAGE_NAME):$(params.ENV)

        echo "Waiting for deployment to roll out"
        if [ "$(params.OBJECT)" = "sts" ]; then
          oc rollout restart $(params.OBJECT)/$(params.IMAGE_NAME) -n $(params.PROJECT)-$(params.ENV)
        fi

        oc rollout status --watch --timeout=$(params.TIMEOUT) $(params.OBJECT)/$(params.IMAGE_NAME) -n $(params.PROJECT)-$(params.ENV)
