---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-dev

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: editor-sso
    patch: |-
      - op: replace
        path: /data/keycloak.json
        value: '{
            "realm": "mmi",
            "auth-server-url": "https://dev.loginproxy.gov.bc.ca/auth/",
            "ssl-required": "external",
            "resource": "mmi-app",
            "public-client": true,
            "verify-token-audience": true,
            "use-resource-role-mappings": true,
            "confidential-port": 0
          }'
  - target:
      kind: Route
      name: editor
    patch: |-
      - op: replace
        path: /spec/host
        value: tno-dev.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: editor-tls
    patch: |-
      - op: replace
        path: /spec/host
        value: dev.editor.mmi.gov.bc.ca
  - target:
      kind: Deployment
      name: editor
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.apps.silver.devops.gov.bc.ca/9b301c-tools/editor:dev
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 40m
