---
# Configuration settings
kind: ConfigMap
apiVersion: v1
metadata:
  name: transcription-service
  namespace: default
  annotations:
    description: Transcription service configuration settings
    created-by: jeremy.foster
  labels:
    name: transcription-service
    part-of: tno
    version: 1.0.0
    component: transcription-service
    managed-by: kustomize
type: Opaque
data:
  KAFKA_CLIENT_ID: Transcription
  MAX_FAIL_LIMIT: "5"
  TOPICS: transcribe
  VOLUME_PATH: /data
  NOTIFICATION_TOPIC: ""
  CHES_EMAIL_ENABLED: "true"
  CHES_EMAIL_AUTHORIZED: "true"
