kind: ConfigMap
apiVersion: v1
metadata:
  name: reporting-azure-ai
  namespace: default
  annotations:
    description: Shared Reporting configuration settings
    created-by: jeremy.foster
  labels:
    name: reporting-azure-ai
    part-of: tno
    version: 1.0.0
    component: reporting-azure-ai
    managed-by: kustomize
data:
  ProjectEndpoint: https://mmi-ai-foundry-east-us-2.openai.azure.com/openai/v1/chat/completions
  DefaultModelDeploymentName: gpt-5.1-chat
  DefaultSystemPrompt: "You are a report writer.  Review the report data and generate summaries and analysis.  The report data is JSON, each section groups related content and contains an array of story records. The `content.text` property contains the story information.  The output generated must be in simple HTML that works within Outlook email client.  Place all the output in a <div>{output}</div>."
  DefaultUserPrompt: 'Create an executive summary of the report data.  Do not start the response with a heading.  The summary should be the first paragraph.  If the output includes a breakdown of related stories, use the heading "Topics".  Do not state your intention, simply summarize the data.'
