debug: false

server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: "off"

  profiles:
    active: default

service:
  max-failed-attempts: ${MAX_FAILED_ATTEMPTS:3}
  failed-delay: ${FAILED_DELAY:5000}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM:tno}
  resource: ${KEYCLOAK_CLIENT_ID:tno-api}
  public-client: true

api:
  host-url: ${API_HOST_URL}
  authority-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    group-id: ${KAFKA_GROUP_ID}
    topics: ${KAFKA_CONSUMER_TOPICS}
    poll-timeout: ${KAFKA_POLL_TIMEOUT:5000}
    enable-auto-commit: ${ENABLE_AUTO_COMMIT:false}
    auto-offset-reset: ${AUTO_OFFSET_RESET:earliest}
  producer:
    client-id: ${KAFKA_CLIENT_ID}
    topic: ${KAFKA_PRODUCER_TOPIC}
