---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
#   - envs:
#       - config.env
#     name: services

patches:
  - target:
      kind: Deployment
      name: syndication-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from": {"kind": "ImageStreamTag", "name": "syndication-service:prod", "namespace": "9b301c-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"syndication-service\")].image"}]'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 20m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 40m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 196Mi
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: Production
