---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - pvc.yaml
  - config-map.yaml
  # - services-config-map.yaml
  - deploy.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true
