---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-dev

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: subscriber-sso
    patch: |-
      - op: replace
        path: /data/keycloak.json
        value: '{
            "realm": "mmi",
            "auth-server-url": "https://dev.loginproxy.gov.bc.ca/auth/",
            "ssl-required": "external",
            "resource": "mmi-app",
            "public-client": true,
            "verify-token-audience": true,
            "use-resource-role-mappings": true,
            "confidential-port": 0
          }'
  - target:
      kind: Route
      name: subscriber
    patch: |-
      - op: replace
        path: /spec/host
        value: mmi-dev.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: subscriber-0
    patch: |-
      - op: replace
        path: /spec/host
        value: mmi-dev-0.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: subscriber-1
    patch: |-
      - op: replace
        path: /spec/host
        value: mmi-dev-1.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: subscriber-2
    patch: |-
      - op: replace
        path: /spec/host
        value: mmi-dev-2.apps.silver.devops.gov.bc.ca
  - target:
      kind: Route
      name: subscriber-tls
    patch: |-
      - op: replace
        path: /spec/host
        value: dev.mmi.gov.bc.ca
  - target:
      kind: DeploymentConfig
      name: subscriber
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 20m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 50Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 100Mi
      - op: replace
        path: /spec/triggers/1/imageChangeParams/from/name
        value: subscriber:dev
