---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: ConfigMap
      name: content-tno-service
    patch: |-
      - op: replace
        path: /data/CHES_FROM
        value: Media Monitoring Insights <mmi@gov.bc.ca>
  - target:
      kind: DeploymentConfig
      name: content-tno-service
    patch: |-
      # - op: replace
      #   path: /spec/replicas
      #   value: 1
      - op: replace
        path: /spec/triggers/1/imageChangeParams/from/name
        value: content-tno-service:prod
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Service__ContentTopics
          value: "TNO-HISTORIC"
