---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: api-services
    patch: |-
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
      - op: replace
        path: /spec/template/spec/containers/0/env/15/valueFrom/secretKeyRef/name
        value: moonstep
      - op: replace
        path: /spec/template/spec/containers/0/env/16/valueFrom/secretKeyRef/name
        value: moonstep
      - op: replace
        path: /spec/template/spec/containers/0/env/17/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/18/valueFrom/secretKeyRef/name
        value: elastic-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/19/valueFrom/secretKeyRef/name
        value: elastic-cloud
      - op: add
        path: /spec/template/spec/containers/0/env/20
        value:
          name: Elastic__ApiKey
          valueFrom:
            secretKeyRef:
              key: ApiKey
              name: elastic-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/21/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/22/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from": {"kind": "ImageStreamTag", "name": "api-services:prod", "namespace": "9b301c-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"api-services\")].image"}]'
