---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: DeploymentConfig
      name: image-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 15m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 75Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 35m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 120Mi
      - op: replace
        path: /spec/triggers/1/imageChangeParams/from/name
        value: image-service:prod
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: Production
