---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: nginx-editor
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/9b301c-tools/nginx-editor:dev
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 20m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 35Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 40m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 100Mi
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from": {"kind": "ImageStreamTag", "name": "nginx-editor:dev", "namespace": "9b301c-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"nginx-reverse-proxy\")].image"}]'
  - target:
      kind: Deployment
      name: nginx-subscriber
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/9b301c-tools/nginx-subscriber:dev
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 20m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 35Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 40m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 100Mi
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from": {"kind": "ImageStreamTag", "name": "nginx-subscriber:dev", "namespace": "9b301c-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"nginx-reverse-proxy\")].image"}]'
