---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-test

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Service
      name: indexing-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/component
        value: indexing-service-cloud
      - op: replace
        path: /spec/selector/component
        value: indexing-service-cloud
  - target:
      kind: ConfigMap
      name: indexing-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/component
        value: indexing-service-cloud
      - op: replace
        path: /data/KAFKA_CLIENT_ID
        value: IndexingCloud
      - op: replace
        path: /data/ELASTICSEARCH_URI
        value: https://test-mmi.es.ca-central-1.aws.elastic-cloud.com
        value_old: https://b2db74af434a489f9bfa8a55de3430a9.ca-central-1.aws.elastic-cloud.com
      - op: replace
        path: /data/CONTENT_INDEX
        value: content
      - op: replace
        path: /data/PUBLISHED_INDEX
        value: published_content
      - op: replace
        path: /data/INDEX_ONLY
        value: "true"
  - target:
      kind: Deployment
      name: indexing-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/name
        value: indexing-service-cloud
      - op: replace
        path: /metadata/labels/component
        value: indexing-service-cloud
      - op: replace
        path: /spec/selector/matchLabels/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/selector/matchLabels/component
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/metadata/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/metadata/labels/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/metadata/labels/component
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/8/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/10/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/12/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/14/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/15/valueFrom/secretKeyRef/name
        value: elastic-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/16/valueFrom/secretKeyRef/name
        value: elastic-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/17/valueFrom/secretKeyRef/name
        value: elastic-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/18/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/19/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/20/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/21/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/22/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/23/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/25/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/template/spec/containers/0/env/26/valueFrom/configMapKeyRef/name
        value: indexing-service-cloud
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 80Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 250Mi
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/9b301c-tools/indexing-service:test
      - op: replace
        path: /metadata/annotations/image.openshift.io~1triggers
        value: '[{"from": {"kind": "ImageStreamTag", "name": "indexing-service:test", "namespace": "9b301c-tools"}, "fieldPath": "spec.template.spec.containers[?(@.name==\"indexing-service-cloud\")].image"}]'
