---
# Configuration settings
kind: ConfigMap
apiVersion: v1
metadata:
  name: nlp-service
  namespace: default
  annotations:
    description: Audio Capture service configuration settings
    created-by: jeremy.foster
  labels:
    name: nlp-service
    part-of: tno
    version: 1.0.0
    component: nlp-service
    managed-by: kustomize
data:
  KAFKA_CLIENT_ID: NLP
  MAX_FAIL_LIMIT: "5"
  TOPICS: nlp
  INDEXING_TOPIC: index
  CHES_EMAIL_ENABLED: "true"
  CHES_EMAIL_AUTHORIZED: "true"
